# Generated by Django 5.1.3 on 2025-02-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='avatar',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cidade',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='data_nascimento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='estado',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
