# Generated by Django 5.1.3 on 2025-01-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('carga_horaria', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=500)),
                ('categoria', models.CharField(max_length=100)),
                ('nivel', models.CharField(max_length=100)),
                ('capa', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
