# Generated by Django 4.2.24 on 2025-09-23 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=400)),
                ('capa', models.ImageField(blank=True, upload_to='')),
                ('link', models.CharField(max_length=200)),
                ('texto', models.TextField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AulaProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='aulas/videos/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='aulas/pdfs/')),
                ('ppt', models.FileField(blank=True, null=True, upload_to='aulas/ppts/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('carga_horaria', models.TimeField(max_length=100)),
                ('descricao', models.TextField(max_length=500)),
                ('categoria', models.CharField(choices=[('Planilha', 'Planilha'), ('Texto', 'Texto'), ('Apresentação', 'Apresentação'), ('Design', 'Design')], max_length=100)),
                ('nivel', models.CharField(choices=[('Fácil', 'Fácil'), ('Médio', 'Médio'), ('Difícil', 'Difícil')], default='Fácil', max_length=30)),
                ('capa', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='CursoProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(upload_to='cursos_professor/')),
                ('categoria', models.CharField(choices=[('Planilha', 'Planilha'), ('Texto', 'Texto'), ('Apresentação', 'Apresentação'), ('Design', 'Design')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Salvos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cursos', models.ManyToManyField(blank=True, related_name='salvos', to='infohelp.curso')),
            ],
        ),
    ]
