# Generated by Django 4.2.24 on 2025-09-23 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('infohelp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salvos',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salvos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cursoprofessor',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_professor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='curso',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aulaprofessor',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='infohelp.cursoprofessor'),
        ),
        migrations.AddField(
            model_name='aulaprofessor',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aula',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infohelp.curso'),
        ),
    ]
