# Generated by Django 5.1.3 on 2025-01-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infohelp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='descricao',
            field=models.TextField(max_length=500),
        ),
    ]
