# Generated by Django 4.2.24 on 2025-09-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infohelp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aulaprofessor',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='capas_aulas_professor/'),
        ),
        migrations.AddField(
            model_name='aulaprofessor',
            name='videoyt',
            field=models.URLField(blank=True, null=True),
        ),
    ]
