# Generated by Django 5.1.3 on 2025-01-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infohelp', '0002_alter_curso_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='carga_horaria',
            field=models.TimeField(max_length=100),
        ),
    ]
