# Generated by Django 5.1.3 on 2025-01-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infohelp', '0003_alter_curso_carga_horaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=200)),
                ('capa', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
