# Generated by Django 5.1.3 on 2025-01-24 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infohelp', '0004_aula'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='aula',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='infohelp.curso'),
        ),
    ]
