# Generated by Django 5.1.3 on 2025-01-24 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infohelp', '0007_remove_curso_aula_aula_aula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aula',
            old_name='aula',
            new_name='curso',
        ),
    ]
