# Generated by Django 5.1.3 on 2025-01-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infohelp', '0015_remove_curso_aula_aula_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='curso',
        ),
        migrations.AddField(
            model_name='aula',
            name='curso',
            field=models.ManyToManyField(null=True, to='infohelp.curso'),
        ),
    ]
