# Generated by Django 5.1.3 on 2025-02-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infohelp', '0019_aula_texto_alter_aula_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='link',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='aula',
            name='texto',
            field=models.TextField(max_length=2000),
        ),
    ]
