# Generated by Django 5.1.3 on 2025-02-05 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infohelp', '0020_alter_aula_link_alter_aula_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infohelp.curso'),
        ),
    ]
