# Generated by Django 5.1.3 on 2025-02-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infohelp', '0021_alter_aula_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('M', 'Médio'), ('P', 'Fácil'), ('G', 'Difícil')], default='M', max_length=30),
        ),
    ]
