# Generated by Django 5.1.3 on 2025-02-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infohelp', '0023_alter_curso_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('Difícil', 'Difícil'), ('Fácil', 'Fácil'), ('Médio', 'Médio')], default='Fácil', max_length=30),
        ),
    ]
