# Generated by Django 5.1.3 on 2025-02-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infohelp', '0025_alter_curso_categoria_alter_curso_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='categoria',
            field=models.CharField(choices=[('Design', 'Design'), ('Apresentação', 'Apresentação'), ('Texto', 'Texto'), ('Planilha', 'Planilha')], default='Texto', max_length=100),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('Médio', 'Médio'), ('Difícil', 'Difícil'), ('Fácil', 'Fácil')], default='Fácil', max_length=30),
        ),
    ]
