# Generated by Django 5.1.3 on 2025-02-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infohelp', '0027_alter_curso_categoria_alter_curso_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='categoria',
            field=models.CharField(choices=[('Design', 'Design'), ('Planilha', 'Planilha'), ('Apresentação', 'Apresentação'), ('Texto', 'Texto')], max_length=100),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('Difícil', 'Difícil'), ('Médio', 'Médio'), ('Fácil', 'Fácil')], default='Fácil', max_length=30),
        ),
    ]
