# Generated by Django 5.1.3 on 2025-02-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infohelp', '0029_alter_curso_categoria_alter_curso_nivel_salvos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='categoria',
            field=models.CharField(choices=[('Planilha', 'Planilha'), ('Apresentação', 'Apresentação'), ('Design', 'Design'), ('Texto', 'Texto')], max_length=100),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('Difícil', 'Difícil'), ('Fácil', 'Fácil'), ('Médio', 'Médio')], default='Fácil', max_length=30),
        ),
    ]
