# Generated by Django 5.1.3 on 2025-02-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infohelp', '0030_alter_curso_categoria_alter_curso_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='categoria',
            field=models.CharField(choices=[('Texto', 'Texto'), ('Apresentação', 'Apresentação'), ('Planilha', 'Planilha'), ('Design', 'Design')], max_length=100),
        ),
        migrations.AlterField(
            model_name='salvos',
            name='cursos',
            field=models.ManyToManyField(blank=True, null=True, related_name='salvos', to='infohelp.curso'),
        ),
    ]
