# Generated by Django 5.1.3 on 2025-02-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infohelp', '0031_alter_curso_categoria_alter_salvos_cursos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='categoria',
            field=models.CharField(choices=[('Design', 'Design'), ('Apresentação', 'Apresentação'), ('Planilha', 'Planilha'), ('Texto', 'Texto')], max_length=100),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('Médio', 'Médio'), ('Difícil', 'Difícil'), ('Fácil', 'Fácil')], default='Fácil', max_length=30),
        ),
        migrations.AlterField(
            model_name='salvos',
            name='cursos',
            field=models.ManyToManyField(blank=True, related_name='salvos', to='infohelp.curso'),
        ),
    ]
