# Generated by Django 5.1.3 on 2025-02-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infohelp', '0032_alter_curso_categoria_alter_curso_nivel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='categoria',
            field=models.CharField(choices=[('Design', 'Design'), ('Texto', 'Texto'), ('Planilha', 'Planilha'), ('Apresentação', 'Apresentação')], max_length=100),
        ),
    ]
