# Generated by Django 5.1.3 on 2025-02-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infohelp', '0036_alter_curso_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('Fácil', 'Fácil'), ('Difícil', 'Difícil'), ('Médio', 'Médio')], default='Fácil', max_length=30),
        ),
    ]
