# Generated by Django 5.1.3 on 2025-02-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infohelp', '0037_alter_curso_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('Médio', 'Médio'), ('Difícil', 'Difícil'), ('Fácil', 'Fácil')], default='Fácil', max_length=30),
        ),
    ]
