# Generated by Django 5.1.3 on 2025-02-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infohelp', '0039_alter_curso_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='texto',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('Difícil', 'Difícil'), ('Fácil', 'Fácil'), ('Médio', 'Médio')], default='Fácil', max_length=30),
        ),
    ]
