# Generated by Django 5.1.3 on 2025-02-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infohelp', '0041_alter_curso_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('Médio', 'Médio'), ('Fácil', 'Fácil'), ('Difícil', 'Difícil')], default='Fácil', max_length=30),
        ),
    ]
