# Generated by Django 5.1.3 on 2025-02-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infohelp', '0042_alter_curso_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='descricao',
            field=models.TextField(max_length=300),
        ),
    ]
