# Generated by Django 5.1.3 on 2025-09-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infohelp', '0044_alter_aula_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(upload_to='cursos_professor/')),
                ('categoria', models.CharField(choices=[('Planilha', 'Planilha'), ('Texto', 'Texto'), ('Apresentação', 'Apresentação'), ('Design', 'Design')], max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('Fácil', 'Fácil'), ('Médio', 'Médio'), ('Difícil', 'Difícil')], default='Fácil', max_length=30),
        ),
    ]
